{% set version = "0.32.2" %}

package:
  name: larrayenv
  version: {{ version }}

build:
  # we cannot have a noarch package because of the conditional dependency on xlwings
  number: 1

requirements:
  host:
    - python
    - pip

  run:
    - python
    - larray =={{ version }}
    - larray-editor =={{ version }}
    - larray_eurostat =={{ version }}
    - qtconsole
    - matplotlib
    - pyqt
    - qtpy
    - pytables
    - xlsxwriter
    - xlrd
    - openpyxl
    - xlwings  # [win or osx]

test:
  imports:
    - larray
    - larray_editor

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0-only
  license_family: GPL
  license_file: '{{ RECIPE_DIR }}/LICENSE'
  summary: "Meta-package to install LArray and all its optional dependencies"
  doc_url: http://larray.readthedocs.io/
  dev_url: http://github.com/larray-project/larray

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
