travis:
  secure:
    BINSTAR_TOKEN: sc/1giBW84/Q4dxDw74taKwwjXu21oE48VpRvLLuOQCcPxwXROfYhsysWKji+aIxki4wzeD4hS0WdvQ7tFvEP2dadqLCHJfQeKWqbc4lv6ivaRj5sSuNMnqaE6KVD8pARehVwaH/pslZxNmvMFeWT0Gc5Uz14o4vQCIak5NcNzQhtyQG+YUnvXEEUSUAc1KqkZqU+wXWKdLne/P+y5hX6gYtIWYEdFlmDlAWkvw5L1HHxn8uDUZtKUJuXC4jMVH/Sd6hSMSB0805xa3YwNmDhut3VXfH7KawRNpZwFb3rUNTyNOSYS5J7aLc7ylHPkIswaKTMDC79pG9Am7DmXF/mko81m4Y3q0JLUNQgER6hrF/81oHsAPfDkwLmKYWWNnp+XZGOiAjdVvtIUdTuRbyuGhmRe/8DfZtKowmsTzBK9UbIFHrMyUAVp9Jz4Lmx1yus+G3RTR6GPfs9r40y7KpB41mgYFXxSmIWmVcJz5iTH0HDE26ZQ/1bGM0Y0WI9apLASAG+MkfCkCFVFIOpBu4iHmKZAF0sZQtZOBK/w3o9+uYWYwT0Wm4idfW/n51v/0+43YC5xPHQkl2GRKgqzzzFwkIj8CX2x4ek5eLOXof3rsRR0BSDT0U3JfHsxG/Tlz6iBxDSskyZx/cE1CyksyKZajmJKBAnX2vrK9RPgWCc/c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
