travis:
  secure:
    BINSTAR_TOKEN: oQtBoeqFYlTm6ieAT3bmnWWHixsztFIcFF++xs4KXiY7umv/jvTHDQv0N6C0j1lvJFIAk0Zq0f6RNbH09QuLFC0foqciI5k4Dfu9zREVZqUyGD/FbGCFQrRnQwCRY30UtV1tuf/ZBYaTqSrB1rwB8jc53NS2TQR4iKQy3sX5pSAE3UVY/5XvRbtGaJZTSgkGDq1mwcQm/mc3S9Wt1KgxaeioLewtH6Ha8zoPMcPCSGF/bqWqV4vls3N2kN36dAn9HPRO/Lj06Cf5DBjxlJ2iQNQTKTyVLmOSxmW5oeP5SewkbDeuEAmGlTG+sqXZT4V9HKynIsww+OucN0UknD5txqunc5G7AZCLCeIDfZVIaCEONVseRScjDjIHHxTTs/nl3on/PoXph2VT0gj0E0bboylwosKOeuHjp/NtB7lMwZfZKKj/27E7SXKFZgSi8i7fsowS9rPt95thjTSI/f59DRlDZl1gOrHiPIu7kc3ur4GIVHa+w5IFSaChcYaSD5YyfhpRUTbYK22XxdKX4Z1AIl9CYaT3lEC91fKrQzJ2PNKn2+WiUjRsLOsZkHeg6K97EVol83mj+VTd9gOhHdMg1pAoh1TBelNA8R8kK25+itNrQVhXqB9wwhklGkCCsm9XzI/uBGos99M4V0lv4ItF5dEWno313VmRH8E9YPipHYM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
